export const MessageTypes = new Map([
  [0x80, 'Note Off'],
  [0x90, 'Note On'],
  [0xa0, 'Key Pressure'],
  [0xb0, 'Control Change'],
  [0xc0, 'Program Change'],
  [0xd0, 'Channel Pressure'],
  [0xe0, 'Pitch Bend'],
  [0xf0, 'System Exclusive'],
  [0xf1, 'Midi Time Code'],
  [0xf2, 'Song Position'],
  [0xf3, 'Song Select'],
  [0xf6, 'Tune Request'],
  [0xf8, 'Clock'],
  [0xfa, 'Start'],
  [0xfb, 'Continue'],
  [0xfc, 'Stop'],
  [0xfe, 'Active Sensing'],
  [0xff, 'Reset'],
]);
